apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: mcmc-lafms-webapp
  name: mcmc-lafms-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: mcmc-lafms-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mcmc-lafms-webapp
    spec:
      containers:
      - image: syafiqpipe/mcmc-lafms-webapp:latest
        imagePullPolicy: Always   
        name: mcmc-lafms-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30