apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcmc-lafms-api-celery-beat
  labels:
    deployment: mcmc-lafms-api-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mcmc-lafms-api-celery-beat
  template:
    metadata:
      labels:
        pod: mcmc-lafms-api-celery-beat
    spec:
      containers:
        - name: mcmc-lafms-api-celery-beat
          image: syafiqpipe/mcmc-lafms-api
          # celery -A mcmc-lafmsapi beat -l debug
          command: ['celery', '-A', 'core', 'beat', '-l', 'debug']
          envFrom:
            - secretRef:
                name: mcmc-lafms-api-secret   