# Generated by Django 2.2.6 on 2020-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={},
        ),
        migrations.AddField(
            model_name='notifications',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
