# Generated by Django 2.2.6 on 2020-07-09 01:18

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.helpers.PathAndRename('images')),
        ),
    ]
