# Generated by Django 2.2.6 on 2020-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('US', 'User'), ('RM', 'Reinforment Monitoring Department'), ('RA', 'Revenue Archive Department'), ('LD', 'Licensing Department')], default='US', max_length=2),
        ),
    ]
