# Generated by Django 2.2.6 on 2020-07-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='office_number',
        ),
    ]
