# Generated by Django 2.2.6 on 2020-07-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apibasic',
            name='home_number',
        ),
    ]
