# Generated by Django 2.2.6 on 2020-07-20 01:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='application_status',
            field=models.CharField(choices=[('CO', 'Company'), ('PA', 'Partnership'), ('IN', 'Individual'), ('SO', 'Society'), ('OT', 'Others')], default='CO', max_length=2),
        ),
        migrations.AddField(
            model_name='license',
            name='company_status',
            field=models.CharField(choices=[('CO', 'Company'), ('PA', 'Partnership'), ('IN', 'Individual'), ('SO', 'Society'), ('OT', 'Others')], default='CO', max_length=2),
        ),
        migrations.AlterField(
            model_name='license',
            name='office_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
