# Generated by Django 2.2.6 on 2020-07-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_auto_20200720_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='count_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
