# Generated by Django 2.2.6 on 2020-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_auto_20200720_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='licence_details_type',
            field=models.CharField(choices=[('NEW', 'New'), ('REN', 'Renewal'), ('VSL', 'Variation of Special licence condition'), ('TRA', 'Transfer'), ('SUR', 'Surrender'), ('COP', 'Change of particulars'), ('ROL', 'Replacement of licence'), ('CLR', 'Copy of Licence Request'), ('RER', 'Re-Registration'), ('CRN', 'Copy of registration notice request')], default='NEW', max_length=3),
        ),
        migrations.AddField(
            model_name='license',
            name='licence_type',
            field=models.CharField(choices=[('IL', 'Individual License'), ('CL', 'Class License')], default='IL', max_length=2),
        ),
        migrations.AlterField(
            model_name='license',
            name='application_status',
            field=models.CharField(choices=[('RE', 'Reviewed'), ('NA', 'New Application'), ('EV', 'Evaluated'), ('AP', 'Approved'), ('OT', 'Others')], default='CO', max_length=2),
        ),
        migrations.AlterField(
            model_name='license',
            name='nric',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
