# Generated by Django 2.2.6 on 2020-07-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_auto_20200720_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='application_status',
            field=models.CharField(choices=[('NA', 'New Application'), ('RE', 'Reviewed'), ('RJ', 'Rejected'), ('EV', 'Evaluated'), ('AP', 'Approved'), ('CO', 'Completed')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='license',
            name='licence_details_type',
            field=models.CharField(choices=[('NE', 'New'), ('RE', 'Renewal'), ('VS', 'Variation of Special licence condition'), ('TR', 'Transfer'), ('SU', 'Surrender'), ('CO', 'Change of particulars'), ('RO', 'Replacement of licence'), ('CL', 'Copy of Licence Request'), ('RR', 'Re-Registration'), ('CR', 'Copy of registration notice request')], default='NE', max_length=2),
        ),
    ]
