# Generated by Django 2.2.6 on 2020-07-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
